[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "aiogram-broadcaster"
dynamic = ["version"]
description = "A lightweight aiogram-based library for broadcasting Telegram messages."
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
authors = [
    { name = "LORES" },
]
dependencies = [
    "redis>=5.0.0",
    "aiogram>=3.0.0"
]

[project.urls]
Source = "https://github.com/loRes228/aiogram_broadcaster"

[project.optional-dependencies]
dev = [
    "mypy>=1.8.0",
    "ruff>=0.2.0"
]

[tool.hatch.version]
path = "aiogram_broadcaster/__about__.py"
