[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "aiogram_broadcaster"
dynamic = ["version"]
description = "A lightweight aiogram-based library for broadcasting Telegram messages."
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
authors = [
    { name = "LORES" },
]
dependencies = [
    "aiogram>=3.4.0"
]

[project.urls]
Source = "https://github.com/loRes228/aiogram_broadcaster"

[project.optional-dependencies]
dev = [
    "mypy>=1.9.0",
    "ruff>=0.3.2",
    "types-aiofiles>=23.2.0"
]
redis = [
    "redis[hiredis]~=5.0.1",
]

[tool.hatch.version]
path = "aiogram_broadcaster/__meta__.py"
