cache-dir = ".cache/ruff"

target-version = "py38"
line-length = 99

preview = true
show-fixes = true
respect-gitignore = false
output-format = "full"

namespace-packages = [
    "examples"
]


[format]
docstring-code-format = true

[lint]
select = ["ALL"]
ignore = [
    "D", # pydocstyle
    "CPY", # flake8-copyright
    "FA", # flake8-future-annotations
    "INT", # flake8-gettext
    "PD", # pandas-vet
    "NPY", # NumPy-specific rules
    "AIR", # Airflow
    "EM", # flake8-errmsg
    "ANN401", # any-type
    "TRY003", # raise-vanilla-args
    "UP006", # non-pep585-annotation
    "PLR6301", # no-self-use
    "PLR0904", # too-many-public-methods
    "PLR0911", # too-many-return-statements
    "PLR0912", # too-many-branches
    "PLR0913", # too-many-arguments
    "PLR0914", # too-many-locals
    "PLR0915", # too-many-statements
    "PLR0916", # too-many-boolean-expressions
    "PLR0917", # too-many-positional
    "PLR1702", # too-many-nested-blocks
]

[lint.isort]
lines-after-imports = 2

[lint.flake8-type-checking]
strict = true

[lint.per-file-ignores]
"tests/**" = ["S101"] # assert
