name: PyPI Publish

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  pypi-publish:
    name: PyPI Publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install dependencies
        run: python -m pip install --upgrade build pip

      - name: Build package
        run: python -m build .

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          skip-existing: true
